/**
 * OpenClaw 2026.6.1 authoritative model catalog snapshot (gateway models.list view="all").
 *
 * Provenance / reproduce:
 *   cd research-claw
 *   OPENCLAW_CONFIG_PATH=<clean-config-no-providers> \
 *     ./node_modules/.bin/openclaw models list --all --json
 *   OC build: 2026.6.1 (2e08f0f), 242 native catalog entries.
 *
 * Shape mirrors the gateway RPC payload: src/gateway/server-methods/models.ts:78
 *   respond(true, { models: ModelCatalogEntry[] })  (runtime "params" stripped)
 * ModelCatalogEntry: src/agents/model-catalog.types.ts
 *
 * Captured from the CLI browse surface, which authoritatively carries
 * contextWindow + input for every entry (242/242 have contextWindow).
 * It does NOT carry reasoning / api / maxTokens:
 *   - maxTokens is not part of ModelCatalogEntry at all (RC keeps its own).
 *   - reasoning / api are present in the live RPC entry but omitted here;
 *     the resolver treats them as optional.
 */

// Single source of truth: the catalog entry shape lives in the prod resolver.
import type { OcModelCatalogEntry } from '../../utils/oc-catalog-align';
export type OcCatalogEntry = OcModelCatalogEntry;

export const OC_CATALOG_OC_VERSION = "2026.6.1 (2e08f0f)";
export const OC_CATALOG_ENTRY_COUNT = 242;

// gateway models.list { view: "all" } payload
export const ocModelsListAllPayload: { models: OcCatalogEntry[] } = {
  models: [
  {"id":"claude-opus-4-6","name":"Claude Opus 4.6","provider":"anthropic","contextWindow":200000,"input":["text","image"]},
  {"id":"claude-opus-4-7","name":"Claude Opus 4.7","provider":"anthropic","contextWindow":200000,"input":["text","image"]},
  {"id":"claude-opus-4-8","name":"Claude Opus 4.8","provider":"anthropic","contextWindow":1048576,"input":["text","image"]},
  {"id":"claude-sonnet-4-6","name":"Claude Sonnet 4.6","provider":"anthropic","contextWindow":200000,"input":["text","image"]},
  {"id":"ark-code-latest","name":"Ark Coding Plan","provider":"byteplus-plan","contextWindow":256000,"input":["text"]},
  {"id":"doubao-seed-code","name":"Doubao Seed Code","provider":"byteplus-plan","contextWindow":256000,"input":["text"]},
  {"id":"glm-4.7","name":"GLM 4.7 Coding","provider":"byteplus-plan","contextWindow":200000,"input":["text"]},
  {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","provider":"byteplus-plan","contextWindow":256000,"input":["text"]},
  {"id":"kimi-k2.5","name":"Kimi K2.5 Coding","provider":"byteplus-plan","contextWindow":256000,"input":["text"]},
  {"id":"glm-4-7-251222","name":"GLM 4.7","provider":"byteplus","contextWindow":200000,"input":["text","image"]},
  {"id":"kimi-k2-5-260127","name":"Kimi K2.5","provider":"byteplus","contextWindow":256000,"input":["text","image"]},
  {"id":"seed-1-8-251228","name":"Seed 1.8","provider":"byteplus","contextWindow":256000,"input":["text","image"]},
  {"id":"gpt-oss-120b","name":"GPT OSS 120B","provider":"cerebras","contextWindow":128000,"input":["text"]},
  {"id":"llama3.1-8b","name":"Llama 3.1 8B","provider":"cerebras","contextWindow":128000,"input":["text"]},
  {"id":"qwen-3-235b-a22b-instruct-2507","name":"Qwen 3 235B Instruct","provider":"cerebras","contextWindow":128000,"input":["text"]},
  {"id":"zai-glm-4.7","name":"Z.ai GLM 4.7","provider":"cerebras","contextWindow":128000,"input":["text"]},
  {"id":"chutesai/Mistral-Small-3.1-24B-Instruct-2503","name":"chutesai/Mistral-Small-3.1-24B-Instruct-2503","provider":"chutes","contextWindow":131072,"input":["text","image"]},
  {"id":"chutesai/Mistral-Small-3.2-24B-Instruct-2506","name":"chutesai/Mistral-Small-3.2-24B-Instruct-2506","provider":"chutes","contextWindow":131072,"input":["text","image"]},
  {"id":"deepseek-ai/DeepSeek-R1-0528-TEE","name":"deepseek-ai/DeepSeek-R1-0528-TEE","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-R1-Distill-Llama-70B","name":"deepseek-ai/DeepSeek-R1-Distill-Llama-70B","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V3","name":"deepseek-ai/DeepSeek-V3","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V3-0324-TEE","name":"deepseek-ai/DeepSeek-V3-0324-TEE","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V3.1-TEE","name":"deepseek-ai/DeepSeek-V3.1-TEE","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V3.1-Terminus-TEE","name":"deepseek-ai/DeepSeek-V3.1-Terminus-TEE","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V3.2-TEE","name":"deepseek-ai/DeepSeek-V3.2-TEE","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"MiniMaxAI/MiniMax-M2.5-TEE","name":"MiniMaxAI/MiniMax-M2.5-TEE","provider":"chutes","contextWindow":196608,"input":["text"]},
  {"id":"moonshotai/Kimi-K2.5-TEE","name":"moonshotai/Kimi-K2.5-TEE","provider":"chutes","contextWindow":262144,"input":["text","image"]},
  {"id":"NousResearch/DeepHermes-3-Mistral-24B-Preview","name":"NousResearch/DeepHermes-3-Mistral-24B-Preview","provider":"chutes","contextWindow":32768,"input":["text"]},
  {"id":"NousResearch/Hermes-4-14B","name":"NousResearch/Hermes-4-14B","provider":"chutes","contextWindow":40960,"input":["text"]},
  {"id":"NousResearch/Hermes-4-405B-FP8-TEE","name":"NousResearch/Hermes-4-405B-FP8-TEE","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE","name":"nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE","provider":"chutes","contextWindow":128000,"input":["text"]},
  {"id":"openai/gpt-oss-120b-TEE","name":"openai/gpt-oss-120b-TEE","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"openai/gpt-oss-20b","name":"openai/gpt-oss-20b","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"Qwen/Qwen2.5-72B-Instruct","name":"Qwen/Qwen2.5-72B-Instruct","provider":"chutes","contextWindow":32768,"input":["text"]},
  {"id":"Qwen/Qwen2.5-Coder-32B-Instruct","name":"Qwen/Qwen2.5-Coder-32B-Instruct","provider":"chutes","contextWindow":32768,"input":["text"]},
  {"id":"Qwen/Qwen2.5-VL-32B-Instruct","name":"Qwen/Qwen2.5-VL-32B-Instruct","provider":"chutes","contextWindow":16384,"input":["text","image"]},
  {"id":"Qwen/Qwen3-14B","name":"Qwen/Qwen3-14B","provider":"chutes","contextWindow":40960,"input":["text"]},
  {"id":"Qwen/Qwen3-235B-A22B-Instruct-2507-TEE","name":"Qwen/Qwen3-235B-A22B-Instruct-2507-TEE","provider":"chutes","contextWindow":262144,"input":["text"]},
  {"id":"Qwen/Qwen3-235B-A22B-Thinking-2507","name":"Qwen/Qwen3-235B-A22B-Thinking-2507","provider":"chutes","contextWindow":262144,"input":["text"]},
  {"id":"Qwen/Qwen3-30B-A3B","name":"Qwen/Qwen3-30B-A3B","provider":"chutes","contextWindow":40960,"input":["text"]},
  {"id":"Qwen/Qwen3-32B","name":"Qwen/Qwen3-32B","provider":"chutes","contextWindow":40960,"input":["text"]},
  {"id":"Qwen/Qwen3-Coder-Next-TEE","name":"Qwen/Qwen3-Coder-Next-TEE","provider":"chutes","contextWindow":262144,"input":["text"]},
  {"id":"Qwen/Qwen3-Next-80B-A3B-Instruct","name":"Qwen/Qwen3-Next-80B-A3B-Instruct","provider":"chutes","contextWindow":262144,"input":["text"]},
  {"id":"Qwen/Qwen3-VL-235B-A22B-Instruct","name":"Qwen/Qwen3-VL-235B-A22B-Instruct","provider":"chutes","contextWindow":262144,"input":["text","image"]},
  {"id":"Qwen/Qwen3.5-397B-A17B-TEE","name":"Qwen/Qwen3.5-397B-A17B-TEE","provider":"chutes","contextWindow":262144,"input":["text","image"]},
  {"id":"Qwen/Qwen3Guard-Gen-0.6B","name":"Qwen/Qwen3Guard-Gen-0.6B","provider":"chutes","contextWindow":128000,"input":["text"]},
  {"id":"rednote-hilab/dots.ocr","name":"rednote-hilab/dots.ocr","provider":"chutes","contextWindow":131072,"input":["text","image"]},
  {"id":"tngtech/DeepSeek-TNG-R1T2-Chimera","name":"tngtech/DeepSeek-TNG-R1T2-Chimera","provider":"chutes","contextWindow":163840,"input":["text"]},
  {"id":"tngtech/R1T2-Chimera-Speed","name":"tngtech/R1T2-Chimera-Speed","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"unsloth/gemma-3-12b-it","name":"unsloth/gemma-3-12b-it","provider":"chutes","contextWindow":131072,"input":["text","image"]},
  {"id":"unsloth/gemma-3-27b-it","name":"unsloth/gemma-3-27b-it","provider":"chutes","contextWindow":128000,"input":["text","image"]},
  {"id":"unsloth/gemma-3-4b-it","name":"unsloth/gemma-3-4b-it","provider":"chutes","contextWindow":96000,"input":["text","image"]},
  {"id":"unsloth/Llama-3.2-1B-Instruct","name":"unsloth/Llama-3.2-1B-Instruct","provider":"chutes","contextWindow":128000,"input":["text"]},
  {"id":"unsloth/Llama-3.2-3B-Instruct","name":"unsloth/Llama-3.2-3B-Instruct","provider":"chutes","contextWindow":128000,"input":["text"]},
  {"id":"unsloth/Mistral-Nemo-Instruct-2407","name":"unsloth/Mistral-Nemo-Instruct-2407","provider":"chutes","contextWindow":131072,"input":["text"]},
  {"id":"unsloth/Mistral-Small-24B-Instruct-2501","name":"unsloth/Mistral-Small-24B-Instruct-2501","provider":"chutes","contextWindow":32768,"input":["text","image"]},
  {"id":"XiaomiMiMo/MiMo-V2-Flash-TEE","name":"XiaomiMiMo/MiMo-V2-Flash-TEE","provider":"chutes","contextWindow":262144,"input":["text"]},
  {"id":"zai-org/GLM-4.6-FP8","name":"zai-org/GLM-4.6-FP8","provider":"chutes","contextWindow":202752,"input":["text"]},
  {"id":"zai-org/GLM-4.6-TEE","name":"zai-org/GLM-4.6-TEE","provider":"chutes","contextWindow":202752,"input":["text"]},
  {"id":"zai-org/GLM-4.6V","name":"zai-org/GLM-4.6V","provider":"chutes","contextWindow":131072,"input":["text","image"]},
  {"id":"zai-org/GLM-4.7-FP8","name":"zai-org/GLM-4.7-FP8","provider":"chutes","contextWindow":202752,"input":["text"]},
  {"id":"zai-org/GLM-4.7-TEE","name":"zai-org/GLM-4.7-TEE","provider":"chutes","contextWindow":202752,"input":["text"]},
  {"id":"zai-org/GLM-5-TEE","name":"zai-org/GLM-5-TEE","provider":"chutes","contextWindow":202752,"input":["text"]},
  {"id":"claude-opus-4-6","name":"Claude Opus 4.6 (Claude CLI)","provider":"claude-cli","contextWindow":200000,"input":["text","image"]},
  {"id":"claude-opus-4-7","name":"Claude Opus 4.7 (Claude CLI)","provider":"claude-cli","contextWindow":200000,"input":["text","image"]},
  {"id":"claude-opus-4-8","name":"Claude Opus 4.8 (Claude CLI)","provider":"claude-cli","contextWindow":1048576,"input":["text","image"]},
  {"id":"claude-sonnet-4-6","name":"Claude Sonnet 4.6 (Claude CLI)","provider":"claude-cli","contextWindow":200000,"input":["text","image"]},
  {"id":"deepseek-ai/DeepSeek-V3.2","name":"DeepSeek V3.2","provider":"deepinfra","contextWindow":163840,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V4-Flash","name":"DeepSeek V4 Flash","provider":"deepinfra","contextWindow":1048576,"input":["text"]},
  {"id":"meta-llama/Llama-3.3-70B-Instruct-Turbo","name":"Llama 3.3 70B Instruct Turbo","provider":"deepinfra","contextWindow":131072,"input":["text"]},
  {"id":"MiniMaxAI/MiniMax-M2.5","name":"MiniMax M2.5","provider":"deepinfra","contextWindow":196608,"input":["text"]},
  {"id":"moonshotai/Kimi-K2.5","name":"Kimi K2.5","provider":"deepinfra","contextWindow":262144,"input":["text","image"]},
  {"id":"nvidia/NVIDIA-Nemotron-3-Super-120B-A12B","name":"NVIDIA Nemotron 3 Super 120B A12B","provider":"deepinfra","contextWindow":262144,"input":["text"]},
  {"id":"stepfun-ai/Step-3.5-Flash","name":"Step 3.5 Flash","provider":"deepinfra","contextWindow":262144,"input":["text"]},
  {"id":"zai-org/GLM-5.1","name":"GLM-5.1","provider":"deepinfra","contextWindow":202752,"input":["text"]},
  {"id":"deepseek-chat","name":"DeepSeek Chat","provider":"deepseek","contextWindow":131072,"input":["text"]},
  {"id":"deepseek-reasoner","name":"DeepSeek Reasoner","provider":"deepseek","contextWindow":131072,"input":["text"]},
  {"id":"deepseek-v4-flash","name":"DeepSeek V4 Flash","provider":"deepseek","contextWindow":1000000,"input":["text"]},
  {"id":"deepseek-v4-pro","name":"DeepSeek V4 Pro","provider":"deepseek","contextWindow":1000000,"input":["text"]},
  {"id":"accounts/fireworks/models/kimi-k2p6","name":"Kimi K2.6","provider":"fireworks","contextWindow":262144,"input":["text","image"]},
  {"id":"accounts/fireworks/routers/kimi-k2p5-turbo","name":"Kimi K2.5 Turbo (Fire Pass)","provider":"fireworks","contextWindow":256000,"input":["text","image"]},
  {"id":"claude-opus-4.6","name":"Claude Opus 4.6","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"claude-opus-4.7","name":"Claude Opus 4.7","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"claude-opus-4.8","name":"Claude Opus 4.8","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"claude-sonnet-4.6","name":"Claude Sonnet 4.6","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gemini-2.5-pro","name":"Gemini 2.5 Pro","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gemini-3-flash","name":"Gemini 3 Flash","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gemini-3.1-pro","name":"Gemini 3.1 Pro","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"goldeneye","name":"Goldeneye","provider":"github-copilot","contextWindow":128000,"input":["text"]},
  {"id":"gpt-5.3-codex","name":"GPT-5.3-Codex","provider":"github-copilot","contextWindow":128000,"input":["text"]},
  {"id":"gpt-5.4","name":"GPT-5.4","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gpt-5.4-mini","name":"GPT-5.4 mini","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gpt-5.4-nano","name":"GPT-5.4 nano","provider":"github-copilot","contextWindow":128000,"input":["text","image"]},
  {"id":"gpt-5.5","name":"GPT-5.5","provider":"github-copilot","contextWindow":400000,"input":["text","image"]},
  {"id":"raptor-mini","name":"Raptor mini","provider":"github-copilot","contextWindow":128000,"input":["text"]},
  {"id":"anthropic/claude-sonnet-4.6","name":"Claude Sonnet 4.6","provider":"gmi","contextWindow":200000,"input":["text","image"]},
  {"id":"deepseek-ai/DeepSeek-V3.2","name":"DeepSeek V3.2","provider":"gmi","contextWindow":163840,"input":["text"]},
  {"id":"google/gemini-3.1-flash-lite","name":"Gemini 3.1 Flash Lite","provider":"gmi","contextWindow":1048576,"input":["text","image"]},
  {"id":"moonshotai/Kimi-K2.5","name":"Kimi K2.5","provider":"gmi","contextWindow":262144,"input":["text","image"]},
  {"id":"openai/gpt-5.4","name":"GPT-5.4","provider":"gmi","contextWindow":400000,"input":["text","image"]},
  {"id":"zai-org/GLM-5.1-FP8","name":"GLM-5.1 FP8","provider":"gmi","contextWindow":202752,"input":["text"]},
  {"id":"compound","name":"Compound","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"compound-mini","name":"Compound Mini","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"llama-3.1-8b-instant","name":"Llama 3.1 8B Instant","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"llama-3.3-70b-versatile","name":"Llama 3.3 70B Versatile","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"meta-llama/llama-4-scout-17b-16e-instruct","name":"Llama 4 Scout 17B","provider":"groq","contextWindow":131072,"input":["text","image"]},
  {"id":"openai/gpt-oss-120b","name":"GPT OSS 120B","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"openai/gpt-oss-20b","name":"GPT OSS 20B","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"openai/gpt-oss-safeguard-20b","name":"Safety GPT OSS 20B","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"qwen/qwen3-32b","name":"Qwen3 32B","provider":"groq","contextWindow":131072,"input":["text"]},
  {"id":"kilo/auto","name":"Kilo Auto","provider":"kilocode","contextWindow":1000000,"input":["text","image"]},
  {"id":"codestral-latest","name":"Codestral (latest)","provider":"mistral","contextWindow":256000,"input":["text"]},
  {"id":"devstral-medium-latest","name":"Devstral 2 (latest)","provider":"mistral","contextWindow":262144,"input":["text"]},
  {"id":"magistral-small","name":"Magistral Small","provider":"mistral","contextWindow":128000,"input":["text"]},
  {"id":"mistral-large-latest","name":"Mistral Large (latest)","provider":"mistral","contextWindow":262144,"input":["text","image"]},
  {"id":"mistral-medium-2508","name":"Mistral Medium 3.1","provider":"mistral","contextWindow":262144,"input":["text","image"]},
  {"id":"mistral-medium-3-5","name":"Mistral Medium 3.5","provider":"mistral","contextWindow":262144,"input":["text","image"]},
  {"id":"mistral-small-latest","name":"Mistral Small (latest)","provider":"mistral","contextWindow":128000,"input":["text","image"]},
  {"id":"pixtral-large-latest","name":"Pixtral Large (latest)","provider":"mistral","contextWindow":128000,"input":["text","image"]},
  {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","provider":"moonshot","contextWindow":262144,"input":["text"]},
  {"id":"kimi-k2-thinking-turbo","name":"Kimi K2 Thinking Turbo","provider":"moonshot","contextWindow":262144,"input":["text"]},
  {"id":"kimi-k2-turbo","name":"Kimi K2 Turbo","provider":"moonshot","contextWindow":256000,"input":["text"]},
  {"id":"kimi-k2.5","name":"Kimi K2.5","provider":"moonshot","contextWindow":262144,"input":["text","image"]},
  {"id":"kimi-k2.6","name":"Kimi K2.6","provider":"moonshot","contextWindow":262144,"input":["text","image"]},
  {"id":"deepseek/deepseek-r1-0528","name":"DeepSeek R1 0528","provider":"novita","contextWindow":163840,"input":["text"]},
  {"id":"deepseek/deepseek-v3-0324","name":"DeepSeek V3 0324","provider":"novita","contextWindow":163840,"input":["text"]},
  {"id":"minimax/minimax-m2.7","name":"MiniMax M2.7","provider":"novita","contextWindow":1000000,"input":["text"]},
  {"id":"moonshotai/kimi-k2.5","name":"Kimi K2.5","provider":"novita","contextWindow":262144,"input":["text","image"]},
  {"id":"qwen/qwen3-235b-a22b-fp8","name":"Qwen3 235B A22B FP8","provider":"novita","contextWindow":262144,"input":["text"]},
  {"id":"zai-org/glm-5","name":"GLM-5","provider":"novita","contextWindow":202752,"input":["text"]},
  {"id":"minimaxai/minimax-m2.5","name":"MiniMax M2.5","provider":"nvidia","contextWindow":196608,"input":["text"]},
  {"id":"minimaxai/minimax-m2.7","name":"Minimax M2.7","provider":"nvidia","contextWindow":196608,"input":["text"]},
  {"id":"moonshotai/kimi-k2.5","name":"Kimi K2.5","provider":"nvidia","contextWindow":262144,"input":["text"]},
  {"id":"nemotron-3-super-120b-a12b","name":"NVIDIA Nemotron 3 Super 120B","provider":"nvidia","contextWindow":262144,"input":["text"]},
  {"id":"z-ai/glm-5.1","name":"GLM 5.1","provider":"nvidia","contextWindow":202752,"input":["text"]},
  {"id":"z-ai/glm5","name":"GLM-5","provider":"nvidia","contextWindow":202752,"input":["text"]},
  {"id":"glm-5.1:cloud","name":"glm-5.1:cloud","provider":"ollama-cloud","contextWindow":128000,"input":["text"]},
  {"id":"kimi-k2.5:cloud","name":"kimi-k2.5:cloud","provider":"ollama-cloud","contextWindow":128000,"input":["text"]},
  {"id":"minimax-m2.7:cloud","name":"minimax-m2.7:cloud","provider":"ollama-cloud","contextWindow":128000,"input":["text"]},
  {"id":"gpt-5.3-chat-latest","name":"GPT-5.3 Chat (latest)","provider":"openai","contextWindow":128000,"input":["text","image"]},
  {"id":"gpt-5.3-codex","name":"GPT-5.3 Codex","provider":"openai","contextWindow":400000,"input":["text","image"]},
  {"id":"gpt-5.4","name":"GPT-5.4","provider":"openai","contextWindow":272000,"input":["text","image"]},
  {"id":"gpt-5.4-mini","name":"GPT-5.4 mini","provider":"openai","contextWindow":400000,"input":["text","image"]},
  {"id":"gpt-5.4-nano","name":"GPT-5.4 nano","provider":"openai","contextWindow":400000,"input":["text","image"]},
  {"id":"gpt-5.4-pro","name":"GPT-5.4 Pro","provider":"openai","contextWindow":1050000,"input":["text","image"]},
  {"id":"gpt-5.5","name":"GPT-5.5","provider":"openai","contextWindow":1000000,"input":["text","image"]},
  {"id":"gpt-5.5-pro","name":"gpt-5.5-pro","provider":"openai","contextWindow":1000000,"input":["text","image"]},
  {"id":"o1","name":"o1","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o1-pro","name":"o1-pro","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o3","name":"o3","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o3-deep-research","name":"o3-deep-research","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o3-mini","name":"o3-mini","provider":"openai","contextWindow":200000,"input":["text"]},
  {"id":"o3-pro","name":"o3-pro","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o4-mini","name":"o4-mini","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"o4-mini-deep-research","name":"o4-mini-deep-research","provider":"openai","contextWindow":200000,"input":["text","image"]},
  {"id":"deepseek-v4-flash","name":"DeepSeek V4 Flash","provider":"opencode-go","contextWindow":1000000,"input":["text"]},
  {"id":"deepseek-v4-pro","name":"DeepSeek V4 Pro","provider":"opencode-go","contextWindow":1000000,"input":["text"]},
  {"id":"deepseek-v3.2","name":"DEEPSEEK V3.2","provider":"qianfan","contextWindow":98304,"input":["text"]},
  {"id":"ernie-5.0-thinking-preview","name":"ERNIE-5.0-Thinking-Preview","provider":"qianfan","contextWindow":119000,"input":["text","image"]},
  {"id":"glm-4.7","name":"glm-4.7","provider":"qwen-oauth","contextWindow":202752,"input":["text"]},
  {"id":"glm-5","name":"glm-5","provider":"qwen-oauth","contextWindow":202752,"input":["text"]},
  {"id":"kimi-k2.5","name":"kimi-k2.5","provider":"qwen-oauth","contextWindow":262144,"input":["text","image"]},
  {"id":"MiniMax-M2.5","name":"MiniMax-M2.5","provider":"qwen-oauth","contextWindow":1000000,"input":["text"]},
  {"id":"qwen3-coder-next","name":"qwen3-coder-next","provider":"qwen-oauth","contextWindow":262144,"input":["text"]},
  {"id":"qwen3-coder-plus","name":"qwen3-coder-plus","provider":"qwen-oauth","contextWindow":1000000,"input":["text"]},
  {"id":"qwen3-max-2026-01-23","name":"qwen3-max-2026-01-23","provider":"qwen-oauth","contextWindow":262144,"input":["text"]},
  {"id":"qwen3.5-plus","name":"qwen3.5-plus","provider":"qwen-oauth","contextWindow":1000000,"input":["text","image"]},
  {"id":"qwen3.6-plus","name":"qwen3.6-plus","provider":"qwen-oauth","contextWindow":1000000,"input":["text","image"]},
  {"id":"step-3.5-flash","name":"Step 3.5 Flash","provider":"stepfun-plan","contextWindow":262144,"input":["text"]},
  {"id":"step-3.5-flash-2603","name":"Step 3.5 Flash 2603","provider":"stepfun-plan","contextWindow":262144,"input":["text"]},
  {"id":"step-3.5-flash","name":"Step 3.5 Flash","provider":"stepfun","contextWindow":262144,"input":["text"]},
  {"id":"hy3-preview","name":"Hy3 preview (TokenHub)","provider":"tencent-tokenhub","contextWindow":256000,"input":["text"]},
  {"id":"deepseek-ai/DeepSeek-V4-Pro","name":"DeepSeek V4 Pro","provider":"together","contextWindow":512000,"input":["text"]},
  {"id":"meta-llama/Llama-3.3-70B-Instruct-Turbo","name":"Llama 3.3 70B Instruct Turbo","provider":"together","contextWindow":131072,"input":["text"]},
  {"id":"moonshotai/Kimi-K2.6","name":"Kimi K2.6 FP4","provider":"together","contextWindow":262144,"input":["text","image"]},
  {"id":"Qwen/Qwen2.5-7B-Instruct-Turbo","name":"Qwen2.5 7B Instruct Turbo","provider":"together","contextWindow":32768,"input":["text"]},
  {"id":"zai-org/GLM-5.1","name":"GLM 5.1 FP4","provider":"together","contextWindow":202752,"input":["text"]},
  {"id":"claude-opus-4-6","name":"Claude Opus 4.6 (via Venice)","provider":"venice","contextWindow":1000000,"input":["text","image"]},
  {"id":"claude-sonnet-4-6","name":"Claude Sonnet 4.6 (via Venice)","provider":"venice","contextWindow":1000000,"input":["text","image"]},
  {"id":"deepseek-v3.2","name":"DeepSeek V3.2","provider":"venice","contextWindow":160000,"input":["text"]},
  {"id":"gemini-3-1-pro-preview","name":"Gemini 3.1 Pro (via Venice)","provider":"venice","contextWindow":1000000,"input":["text","image"]},
  {"id":"gemini-3-flash-preview","name":"Gemini 3 Flash (via Venice)","provider":"venice","contextWindow":256000,"input":["text","image"]},
  {"id":"gemini-3-pro-preview","name":"Gemini 3 Pro (via Venice)","provider":"venice","contextWindow":198000,"input":["text","image"]},
  {"id":"google-gemma-3-27b-it","name":"Google Gemma 3 27B Instruct","provider":"venice","contextWindow":198000,"input":["text","image"]},
  {"id":"grok-41-fast","name":"Grok 4.1 Fast (via Venice)","provider":"venice","contextWindow":1000000,"input":["text","image"]},
  {"id":"hermes-3-llama-3.1-405b","name":"Hermes 3 Llama 3.1 405B","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"kimi-k2-5","name":"Kimi K2.5","provider":"venice","contextWindow":256000,"input":["text","image"]},
  {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","provider":"venice","contextWindow":256000,"input":["text"]},
  {"id":"llama-3.2-3b","name":"Llama 3.2 3B","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"llama-3.3-70b","name":"Llama 3.3 70B","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"minimax-m21","name":"MiniMax M2.1","provider":"venice","contextWindow":198000,"input":["text"]},
  {"id":"minimax-m25","name":"MiniMax M2.5","provider":"venice","contextWindow":198000,"input":["text"]},
  {"id":"mistral-31-24b","name":"Venice Medium (Mistral)","provider":"venice","contextWindow":128000,"input":["text","image"]},
  {"id":"nvidia-nemotron-3-nano-30b-a3b","name":"NVIDIA Nemotron 3 Nano 30B","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"olafangensan-glm-4.7-flash-heretic","name":"GLM 4.7 Flash Heretic","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"openai-gpt-4o-2024-11-20","name":"GPT-4o (via Venice)","provider":"venice","contextWindow":128000,"input":["text","image"]},
  {"id":"openai-gpt-4o-mini-2024-07-18","name":"GPT-4o Mini (via Venice)","provider":"venice","contextWindow":128000,"input":["text","image"]},
  {"id":"openai-gpt-52","name":"GPT-5.2 (via Venice)","provider":"venice","contextWindow":256000,"input":["text"]},
  {"id":"openai-gpt-52-codex","name":"GPT-5.2 Codex (via Venice)","provider":"venice","contextWindow":256000,"input":["text","image"]},
  {"id":"openai-gpt-53-codex","name":"GPT-5.3 Codex (via Venice)","provider":"venice","contextWindow":400000,"input":["text","image"]},
  {"id":"openai-gpt-54","name":"GPT-5.4 (via Venice)","provider":"venice","contextWindow":1000000,"input":["text","image"]},
  {"id":"openai-gpt-oss-120b","name":"OpenAI GPT OSS 120B","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"qwen3-235b-a22b-instruct-2507","name":"Qwen3 235B Instruct","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"qwen3-235b-a22b-thinking-2507","name":"Qwen3 235B Thinking","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"qwen3-4b","name":"Venice Small (Qwen3 4B)","provider":"venice","contextWindow":32000,"input":["text"]},
  {"id":"qwen3-5-35b-a3b","name":"Qwen3.5 35B A3B","provider":"venice","contextWindow":256000,"input":["text","image"]},
  {"id":"qwen3-coder-480b-a35b-instruct","name":"Qwen3 Coder 480B","provider":"venice","contextWindow":256000,"input":["text"]},
  {"id":"qwen3-coder-480b-a35b-instruct-turbo","name":"Qwen3 Coder 480B Turbo","provider":"venice","contextWindow":256000,"input":["text"]},
  {"id":"qwen3-next-80b","name":"Qwen3 Next 80B","provider":"venice","contextWindow":256000,"input":["text"]},
  {"id":"qwen3-vl-235b-a22b","name":"Qwen3 VL 235B (Vision)","provider":"venice","contextWindow":256000,"input":["text","image"]},
  {"id":"venice-uncensored","name":"Venice Uncensored (Dolphin-Mistral)","provider":"venice","contextWindow":32000,"input":["text"]},
  {"id":"zai-org-glm-4.6","name":"GLM 4.6","provider":"venice","contextWindow":198000,"input":["text"]},
  {"id":"zai-org-glm-4.7","name":"GLM 4.7","provider":"venice","contextWindow":198000,"input":["text"]},
  {"id":"zai-org-glm-4.7-flash","name":"GLM 4.7 Flash","provider":"venice","contextWindow":128000,"input":["text"]},
  {"id":"zai-org-glm-5","name":"GLM 5","provider":"venice","contextWindow":198000,"input":["text"]},
  {"id":"ark-code-latest","name":"Ark Coding Plan","provider":"volcengine-plan","contextWindow":256000,"input":["text"]},
  {"id":"doubao-seed-code","name":"Doubao Seed Code","provider":"volcengine-plan","contextWindow":256000,"input":["text"]},
  {"id":"doubao-seed-code-preview-251028","name":"Doubao Seed Code Preview","provider":"volcengine-plan","contextWindow":256000,"input":["text"]},
  {"id":"glm-4.7","name":"GLM 4.7 Coding","provider":"volcengine-plan","contextWindow":200000,"input":["text"]},
  {"id":"kimi-k2-thinking","name":"Kimi K2 Thinking","provider":"volcengine-plan","contextWindow":256000,"input":["text"]},
  {"id":"kimi-k2.5","name":"Kimi K2.5 Coding","provider":"volcengine-plan","contextWindow":256000,"input":["text"]},
  {"id":"deepseek-v3-2-251201","name":"DeepSeek V3.2","provider":"volcengine","contextWindow":128000,"input":["text","image"]},
  {"id":"doubao-seed-1-8-251228","name":"Doubao Seed 1.8","provider":"volcengine","contextWindow":256000,"input":["text","image"]},
  {"id":"doubao-seed-code-preview-251028","name":"doubao-seed-code-preview-251028","provider":"volcengine","contextWindow":256000,"input":["text","image"]},
  {"id":"glm-4-7-251222","name":"GLM 4.7","provider":"volcengine","contextWindow":200000,"input":["text","image"]},
  {"id":"kimi-k2-5-260127","name":"Kimi K2.5","provider":"volcengine","contextWindow":256000,"input":["text","image"]},
  {"id":"mimo-v2-flash","name":"Xiaomi MiMo V2 Flash","provider":"xiaomi","contextWindow":262144,"input":["text"]},
  {"id":"mimo-v2-omni","name":"Xiaomi MiMo V2 Omni","provider":"xiaomi","contextWindow":262144,"input":["text","image"]},
  {"id":"mimo-v2-pro","name":"Xiaomi MiMo V2 Pro","provider":"xiaomi","contextWindow":1048576,"input":["text"]},
  {"id":"glm-4.5","name":"GLM-4.5","provider":"zai","contextWindow":131072,"input":["text"]},
  {"id":"glm-4.5-air","name":"GLM-4.5 Air","provider":"zai","contextWindow":131072,"input":["text"]},
  {"id":"glm-4.5-flash","name":"GLM-4.5 Flash","provider":"zai","contextWindow":131072,"input":["text"]},
  {"id":"glm-4.5v","name":"GLM-4.5V","provider":"zai","contextWindow":64000,"input":["text","image"]},
  {"id":"glm-4.6","name":"GLM-4.6","provider":"zai","contextWindow":204800,"input":["text"]},
  {"id":"glm-4.6v","name":"GLM-4.6V","provider":"zai","contextWindow":128000,"input":["text","image"]},
  {"id":"glm-4.7","name":"GLM-4.7","provider":"zai","contextWindow":204800,"input":["text"]},
  {"id":"glm-4.7-flash","name":"GLM-4.7 Flash","provider":"zai","contextWindow":200000,"input":["text"]},
  {"id":"glm-4.7-flashx","name":"GLM-4.7 FlashX","provider":"zai","contextWindow":200000,"input":["text"]},
  {"id":"glm-5","name":"GLM-5","provider":"zai","contextWindow":202800,"input":["text"]},
  {"id":"glm-5-turbo","name":"GLM-5 Turbo","provider":"zai","contextWindow":202800,"input":["text"]},
  {"id":"glm-5.1","name":"GLM-5.1","provider":"zai","contextWindow":202800,"input":["text"]},
  {"id":"glm-5v-turbo","name":"GLM-5V Turbo","provider":"zai","contextWindow":202800,"input":["text","image"]},
  ],
};
